import Head from "next/head";
import Dashboard from "./components/Dashboard";

import ChartComponent from "./components/Chart";
import CurrencyList from "./Currency";
import Sidebar from "./components/Sidebar";



export default function Home() {
  return (
    <>
      <Head>
        <title>Crypto Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" flex">
        <Sidebar />
        <CurrencyList />
      </div>
    </>
  );
}
